### PR TITLE
Finished cloning the old Apple homepage for the HTML/CSS solo project (project #4)

### PR DESCRIPTION
**Pull request by voscarmv**
For this project, I:

- Used webkit background gradient to style the navbar.
- Used semantic HTML to section my layout.
- Used flex to position the elements of the navbar.
- Used a combination of grid with a nested flexbox to style the footer element.

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @voscarmv, you have done well and your page looks good :+1: . Just one change is required now:**

The four images below the main section should be links. Enclose them in anchor tags

Please, make this adjustment and submit another code review request.

**Comment by voscarmv** [comment]
> **Hi @voscarmv, you have done well and your page looks good 👍 . Just one change is required now:**
> 
> The four images below the main section should be links. Enclose them in anchor tags
> 
> Please, make this adjustment and submit another code review request.

Changes applied. Thanks for the review!

**Review by mosesogwo — APPROVED** [review]
**:trophy:Congratulations. Your project is approved**

You can now merge to master and submit a project completion form.

**Good luck in your future project:smile:**

**Status: Approved.**

**Comment by voscarmv** [comment]
> **🏆Congratulations. Your project is approved**
> 
> You can now merge to master and submit a project completion form.
> 
> **Good luck in your future project😄**
> 
> **Status: Approved.**

That's awesome! Thanks @mosesogwo!

**Pull request merged**
